[package]
name = "catsh-cli"
version = "0.1.0-alpha.0"
description = "A cross-platform shell."
authors = ["Catsh Contributors"]
edition = "2018"
license = "GPL-2.0"
repository = "https://github.com/jheysonsaav/catsh"
default-run = "catsh"

[[bin]]
name = "catsh"
path = "main.rs"

[dependencies]
catsh-core = { path = "../core" }
clap = "2.33.3"

[package.metadata.winres]
OriginalFilename = "catsh.exe"
LegalCopyright = "Copyright (C) Catsh contributors. All right reserved."
ProductName = "Catsh"
FileDescription = "A cross-platform shell."