[package]
name = "catsh-core"
version = "0.1.0-alpha.0"
description = "A cross-platform shell."
authors = ["catsh authors"]
edition = "2018"
license = "GPL-2.0"
repository = "https://github.com/jheysonsaav/catsh"

[lib]
path = "lib.rs"

[dependencies]
directories = "3.0.1"
termcolor = "1.1.2"
lazy_static = "1.4.0"
regex = "1.4.5"