[package]
name = "catsh-core"
version = "0.2.2-alpha.0"
authors = ["Catsh authors"]
edition = "2018"
description = "A cross-platform shell."
readme = "../README.md"
repository = "https://github.com/jheysonsaav/catsh"
license = "GPL-2.0"
keywords = ["shell", "catsh", "windows", "linux", "macos"]
categories = ["command-line-interface", "command-line-utilities"]

[lib]
path = "lib.rs"

[dependencies]
rustyline = "8.0.0"
directories = "3.0.1"
termcolor = "1.1.2"
lazy_static = "1.4.0"
regex = "1.4.5"