name: Ci

on: [push, pull_request]

jobs:
  check:
    name: Checking on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: Install Rustlang v1.51.0
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.51.0

      - uses: actions/checkout@v2

      - name: Versions
        run: |
          rustc --version
          cargo --version

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Testing
        run: cargo test

      - name: Checking
        run: cargo check

      - name: Linting
        run: cargo clippy

      - name: Formatting
        run: cargo fmt

      - name: Pre-release (Testing)
        if: startsWith(github.ref, 'refs/tags/v')
        run: cargo test --release

      - name: Pre-release (Checking)
        if: startsWith(github.ref, 'refs/tags/v')
        run: cargo check --release