name: Ci

on: [push, pull_request]

jobs:
  build:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Install Rustlang v1.51.0
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.51.0

      - uses: actions/checkout@v2

      - name: Versions
        run: |
          rustc --version
          cargo --version
      - name: Testing
        run: |
          cargo check
          cargo test

      - name: Pre-release (Testing)
        run: |
          cargo check --release
          cargo test --release

      - name: Pre-release (Build)
        if: startsWith(github.ref, 'refs/tags/v')
        run: cargo build --release

      - name: Pre-release (Ubuntu)
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'ubuntu')
        run: |
          mkdir catsh-x86_64-unknown-linux-gnu/
          cp -f README.md CHANGELOG.md example/ target/release/catsh catsh-x86_64-unknown-linux-gnu/
          zip -r catsh-x86_64-unknown-linux-gnu.zip catsh-x86_64-unknown-linux-gnu/

      - name: Pre-release (Windows)
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'windows')
        run: |
          New-Item -Path . -Name "catsh-x86_64-pc-windows-msvc" -ItemType "directory"
          Copy-Item -Path "README.md","CHANGELOG.md" -Destination "catsh-x86_64-pc-windows-msvc"
          Compress-Archive -CompressionLevel Optimal -Force -Path target/release/catsh.exe -DestinationPath target/release/catsh-x86_64-pc-windows-msvc.zip

      - name: Pre-release (MacOS)
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'macos')
        run: |
          mkdir catsh-x86_64-apple-darwin/
          cp -f README.md CHANGELOG.md example/ target/release/catsh catsh-x86_64-apple-darwin/
          zip -r catsh-x86_64-apple-darwin.zip catsh-x86_64-apple-darwin/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GIHUB_TOKEN }}
        with:
          files: |
            target/release/catsh-x86_64-unknown-linux-gnu.zip
            target/release/catsh-x86_64-pc-windows-msvc.zip
            target/release/catsh-x86_64-apple-darwin.zip
          body_path: CHANGELOG.md
          draft: true