name: Ci

on: [push, pull_request]

jobs:
  build:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Install Rustlang v1.51.0
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.51.0

      - uses: actions/checkout@v2

      - name: Versions
        run: |
          rustc --version
          cargo --version
          
      - name: Testing
        run: |
          cargo check
          cargo test

      - name: Pre-release (Testing)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cargo check --release
          cargo test --release

      - name: Pre-release (Build)
        if: startsWith(github.ref, 'refs/tags/v')
        run: cargo build --release

      - name: Pre-release (Ubuntu)
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'ubuntu')
        run: |
          mkdir stellar-x86_64-unknown-linux-gnu/
          cp -f README.md target/release/stellar stellar-x86_64-unknown-linux-gnu/
          zip -9r stellar-x86_64-unknown-linux-gnu.zip stellar-x86_64-unknown-linux-gnu/

      - name: Pre-release (Windows)
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'windows')
        run: |
          New-Item -Path . -Name "stellar-x86_64-pc-windows-msvc" -ItemType "directory"
          Copy-Item -Path "README.md" -Destination "stellar-x86_64-pc-windows-msvc"
          Compress-Archive -CompressionLevel Optimal -Force -Path target/release/stellar.exe -DestinationPath stellar-x86_64-pc-windows-msvc.zip

      - name: Pre-release (MacOS)
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'macos')
        run: |
          mkdir stellar-x86_64-apple-darwin/
          cp -f README.md target/release/stellar stellar-x86_64-apple-darwin/
          zip -9r stellar-x86_64-apple-darwin.zip stellar-x86_64-apple-darwin/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          files: |
            stellar-x86_64-unknown-linux-gnu.zip
            stellar-x86_64-pc-windows-msvc.zip
            stellar-x86_64-apple-darwin.zip
          draft: true

      - name: Publish to Cargo
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          startsWith(matrix.os, 'ubuntu')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd core
          cargo publish
          sleep 30
          cd ../cli
          cargo publish